# Generated by Django 3.2.6 on 2021-09-28 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'db_table': 'tblActivities',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetailType',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Detail Types',
                'db_table': 'tblListDetailTypes',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('goal_details', models.TextField()),
                ('goal_after_investment', models.TextField()),
            ],
            options={
                'db_table': 'tblGoals',
            },
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('initiative_short_description', models.TextField()),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiatives', to='implementation.goal')),
            ],
            options={
                'db_table': 'tblInitiatives',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='InputType',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Input Types',
                'db_table': 'tblInputTypes',
            },
        ),
        migrations.CreateModel(
            name='OutputType',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name_plural': 'Output Types',
                'db_table': 'tblOuputTypes',
            },
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='implementation.initiative')),
                ('output_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ouputs', to='implementation.outputtype')),
            ],
            options={
                'db_table': 'tblOuputs',
            },
        ),
        migrations.CreateModel(
            name='InputSubType',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('units', models.CharField(max_length=100)),
                ('input_sub_type_short', models.CharField(max_length=80)),
                ('units_short', models.CharField(max_length=80)),
                ('cost_usd', models.PositiveIntegerField(default=0)),
                ('input_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_sub_types', to='implementation.inputtype')),
            ],
            options={
                'verbose_name_plural': 'Input Subtypes',
                'db_table': 'tblInputSubTypes',
            },
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('notes', models.CharField(max_length=100)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='implementation.activity')),
                ('input_sub_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='implementation.inputsubtype', verbose_name='Input Subtype')),
            ],
            options={
                'db_table': 'tblInputs',
            },
        ),
        migrations.CreateModel(
            name='InitiativeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('detail_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_details', to='implementation.detailtype')),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_details', to='implementation.initiative')),
            ],
            options={
                'verbose_name_plural': 'Initiative Details',
                'db_table': 'tblInitiativeDetails',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='implementation.initiative'),
        ),
    ]
