# Generated by Django 3.2.6 on 2021-09-23 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'tblActivities',
                'verbose_name_plural': 'tblActivities',
                'db_table': 'tblActivities',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DetailType',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'tblListDetailTypes',
                'verbose_name_plural': 'tblListDetailTypes',
                'db_table': 'tblListDetailTypes',
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('goal_details', models.TextField()),
                ('goal_after_investment', models.TextField()),
            ],
            options={
                'verbose_name': 'tblGoals',
                'verbose_name_plural': 'tblGoals',
                'db_table': 'tblGoals',
            },
        ),
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('initiative_short_description', models.TextField()),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiatives', to='implementation.goal')),
            ],
            options={
                'verbose_name': 'tblInitiatives',
                'verbose_name_plural': 'tblInitiatives',
                'db_table': 'tblInitiatives',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OutputType',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'tblListOuputTypes',
                'verbose_name_plural': 'tblListOuputTypes',
                'db_table': 'tblListOuputTypes',
            },
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output', to='implementation.initiative')),
                ('output_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ouput', to='implementation.outputtype')),
            ],
            options={
                'verbose_name': 'tblOuputs',
                'verbose_name_plural': 'tblOuputs',
                'db_table': 'tblOuputs',
            },
        ),
        migrations.CreateModel(
            name='InputType',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_type', to='implementation.activity')),
            ],
            options={
                'verbose_name': 'tblListInputTypes',
                'verbose_name_plural': 'tblListInputTypes',
                'db_table': 'tblListInputTypes',
            },
        ),
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('units', models.CharField(max_length=100)),
                ('input_short', models.CharField(max_length=80)),
                ('units_short', models.CharField(max_length=80)),
                ('cost_usd', models.PositiveIntegerField(default=0)),
                ('input_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_sub_types', to='implementation.inputtype')),
            ],
            options={
                'verbose_name': 'tblListInputs',
                'verbose_name_plural': 'tblListInputs',
                'db_table': 'tblListInputs',
            },
        ),
        migrations.CreateModel(
            name='InitiativeDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('detail_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_details', to='implementation.detailtype')),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_details', to='implementation.initiative')),
            ],
            options={
                'verbose_name': 'tblInitiativeDetails',
                'verbose_name_plural': 'tblInitiativeDetails',
                'db_table': 'tblInitiativeDetails',
            },
        ),
        migrations.CreateModel(
            name='Approach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('notes', models.CharField(max_length=100)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approach', to='implementation.activity')),
            ],
            options={
                'verbose_name': 'tblApproaches',
                'verbose_name_plural': 'tblApproaches',
                'db_table': 'tblApproaches',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='implementation.initiative'),
        ),
    ]
