# Generated by Django 3.2.6 on 2021-09-24 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('implementation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='input_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='implementation.inputtype'),
        ),
        migrations.AlterField(
            model_name='inputtype',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_types', to='implementation.activity'),
        ),
    ]
