# Generated by Django 3.2.7 on 2021-09-29 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('implementation', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='initiativedetail',
            options={'ordering': ['id'], 'verbose_name_plural': 'Initiative Details'},
        ),
        migrations.AlterModelOptions(
            name='input',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='inputtype',
            options={'ordering': ['id'], 'verbose_name_plural': 'Input Types'},
        ),
        migrations.AlterModelOptions(
            name='output',
            options={'ordering': ['id']},
        ),
    ]
