# Generated by Django 3.2.6 on 2021-08-11 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('implementation', '0003_auto_20210811_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='input_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='implementation.inputlist'),
        ),
    ]
