# Generated by Django 3.2.6 on 2021-08-11 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('implementation', '0004_alter_input_input_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='input_name',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='implementation.inputlist'),
        ),
    ]
