# Generated by Django 3.2.6 on 2021-08-11 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('implementation', '0005_alter_input_input_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='input',
            name='input_name',
            field=models.CharField(max_length=255),
        ),
        migrations.DeleteModel(
            name='InputList',
        ),
    ]
