# Generated by Django 3.2.6 on 2021-08-19 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('implementation', '0006_auto_20210811_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_initiative', to='implementation.initiative'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_info', to='implementation.goal'),
        ),
        migrations.AlterField(
            model_name='initiativedetail',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_info', to='implementation.initiative'),
        ),
        migrations.AlterField(
            model_name='input',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_input', to='implementation.activity'),
        ),
        migrations.AlterField(
            model_name='input',
            name='input_sub_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_type', to='implementation.inputsubtype'),
        ),
        migrations.AlterField(
            model_name='inputsubtype',
            name='input_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_sub_info', to='implementation.inputtype'),
        ),
        migrations.AlterField(
            model_name='output',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_output', to='implementation.initiative'),
        ),
        migrations.AlterField(
            model_name='output',
            name='output_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ouput_info_type', to='implementation.outputtype'),
        ),
    ]
