# Generated by Django 3.2.6 on 2021-09-22 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('implementation', '0007_auto_20210819_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='implementation.initiative'),
        ),
        migrations.AlterField(
            model_name='initiative',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiatives', to='implementation.goal'),
        ),
        migrations.AlterField(
            model_name='initiativedetail',
            name='detail_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_details', to='implementation.detailtype'),
        ),
        migrations.AlterField(
            model_name='initiativedetail',
            name='initiative',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='initiative_details', to='implementation.initiative'),
        ),
        migrations.AlterField(
            model_name='input',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='implementation.activity'),
        ),
        migrations.AlterField(
            model_name='input',
            name='input_sub_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inputs', to='implementation.inputsubtype'),
        ),
        migrations.AlterField(
            model_name='inputsubtype',
            name='input_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_sub_types', to='implementation.inputtype'),
        ),
    ]
